dist: trusty
sudo: required
language: python
addons:
  firefox: latest
  apt:
    packages:
      - google-chrome-stable
env:
  global:
  - DISPLAY=:99.0

_version:
  two: &two
    language: python
    python: "2.7"
  three: &three
    language: python
    python: "3.6"

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: latest-esr
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable

matrix:
  include:
  - env: TOXENV=flake8
    <<: *two
  - env: TOXENV=py27-chrome
    <<: *two
    <<: *chrome
  - env: TOXENV=py27-firefox
    <<: *two
    <<: *firefox-nightly
  - env: TOXENV=flake8
    <<: *three
  - env: TOXENV=py36-chrome
    <<: *three
    <<: *chrome
  - env: TOXENV=py36-firefox
    <<: *three
    <<: *firefox-nightly
install:
- pip install tox-travis
before_script:
- firefox --version
- export GECKODRIVER_DOWNLOAD=`curl -s 'https://api.github.com/repos/mozilla/geckodriver/releases/latest' | python -c "import sys, json; r = json.load(sys.stdin); print([a for a in r['assets'] if 'linux64' in a['name']][0]['browser_download_url']);"`
- echo $GECKODRIVER_DOWNLOAD
- curl -L -o geckodriver.tar.gz $GECKODRIVER_DOWNLOAD
- gunzip -c geckodriver.tar.gz | tar xopf -
- chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
- geckodriver --version
- export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
- curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
- unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
- chromedriver --version
- sh -e /etc/init.d/xvfb start
script:
- tox
