dist: trusty
sudo: required
language: python
addons:
  firefox: latest
  apt:
    packages:
      - google-chrome-stable
env:
  global:
  - DISPLAY=:99.0

_version:
  two: &two
    language: python
    python: "2.7"
  three: &three
    language: python
    python: "3.6"

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: latest-esr
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable

matrix:
  include:
  - env: TOXENV=flake8
    <<: *two
  - env: TOXENV=py27-chrome
    <<: *two
    <<: *chrome
  - env: TOXENV=py27-firefox
    <<: *two
    <<: *firefox-nightly
  - env: TOXENV=flake8
    <<: *three
  - env: TOXENV=py36-chrome
    <<: *three
    <<: *chrome
  - env: TOXENV=py36-firefox
    <<: *three
    <<: *firefox-nightly
before_install:
- chmod +x ./travis.sh
install:
- pip install tox-travis
before_script:
- ./travis.sh
script:
- tox
