clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

image:
- Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"

build: false

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install tox
  - pip install -r requirements.txt

build_script:
  - python setup.py install

before_test:
 - chromedriver.exe --version
 - geckodriver.exe --version
 - IEDriverServer.exe --version

test_script:
  - tox -e py27-ie