clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"

build: false

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install tox
  - pip install -r requirements.txt

build_script:
  - python setup.py install

before_test:
 - curl -fsS -o C:\Tools\WebDriver\IEServerDriver.exe https://github.com/SeleniumHQ/selenium/raw/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe
 - chromedriver.exe --version
 - geckodriver.exe --version
 - IEDriverServer.exe --version

test_script:
  - tox py27-ie